config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: %i[destroy]
  resources :movies, only: %i[index new create]

  root to: 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :image

  validates :name, uniqueness: { scope: :user_id}
  validates :name, :image, :user_id, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true
  validates :title, :overview, presence: true

  def self.search(query)
    require 'json'
    require 'open-uri'

    url = ENV['TMBB_BASE_API'] + query.to_s
    movies_serialized = URI.open(url).read
    movies = JSON.parse(movies_serialized)
    movies['results'].each do |m|
      Movie.create(
        title: m['title'],
        overview: m['overview'],
        poster_url: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2#{m['poster_path']}",
        rating: m['vote_average'],
        popularity: m['popularity']
      )
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
    @movie = Movie.find(params[:movie_id])
  end

  def create
    @bookmark = Bookmark.new(bm_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = List.find(@bookmark.list_id)
    @bookmark.list = @list
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bm_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @user = current_user
    @lists = List.where(user_id: @user)
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
    @bookmark = Bookmark.new
    @movie = Movie.new
  end

  def new
    @user = current_user
    @list = List.new
  end

  def create
    @user = current_user
    @list = List.new(list_params)
    @list.user = @user
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @user = current_user
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to lists_path(@list)
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :image)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    list_id = params[:passed_parameter][:list]
    @list = List.find(list_id)
    @bookmark = Bookmark.new
    query = params[:passed_parameter][:query].gsub(/[[:punct:]]/, '%')
    @movies = Movie.where("lower(replace(title, '-', '')) LIKE lower(?)", "%#{query}%").order('popularity DESC')
  end

  def new
    list_id = if params[:passed_parameter]
                params[:passed_parameter][:list_id]
              else
                params[:search][:list_id]
              end
    @list = List.find(list_id)
    if params[:search]
      query = params[:search][:title]
      @movies = Movie.search(query)
      redirect_to movies_path(passed_parameter: { query: params[:search][:title], list: list_id })
    else
      @movies = ''
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a bookmark</h1>
<div class="container bg-light bm-container">
  <div class='col-11 movie-card'>
    <div class="card-category col-4" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @movie.poster_url %>)"></div>
    <div>
      <div class="description">
        <div class="card-h p-1 scroll">
          <h4><%= @movie.title %></h4>
        </div>
        <div class="card-p p-1 scroll">
          <p><%= @movie.overview %></p>
        </div>
      </div>
    </div>
    <button class="btn btn-light btn-movie"><%= icon('fas', 'check')  %></button>
  </div>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.hidden_field :movie_id, value: @movie.id %>
    <%= f.input :comment %>
    <%= f.button :submit, class: 'btn btn-primary btn-sm' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <div class="container">
        <%= render 'shared/flashes' %>
        <%= yield %>
      </div>
      <%= render 'shared/footer' unless current_page?(new_user_session_path) || current_page?(new_user_registration_path) %>
    </div>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Edit list</h1>
<div class="container bg-light col-6">
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :image, as: :file %>
  <%= f.button :submit, class: 'btn btn-primary btn-sm'  %>
<% end %>
</div>
<br>
<%= link_to '< Back', lists_path, class: "btn btn-outline-primary" %>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://images.unsplash.com/photo-1585647347384-2593bc35786b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80');">
  <div class="container">
    <h1>Sal Watch List</h1>
  </div>
</div>
<br>
<div class="d-flex flex-wrap">
  <% @lists.each do |list| %>
    <div class="list-card m-2">
      <%= link_to list.name, list_path(list), class: "link-card text-decoration-none", style:"background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('#{cl_image_path list.image.key, height: 80, crop: :fill}')" %>
      <%= link_to icon('fas', 'edit'), edit_list_path(list), class: 'edit' %>
    </div>
  <% end %>
  <button class='btn btn-outline-primary btn-list m-2' id='show'><%= icon('fas', 'list') + ' Add a new list' %></button>
</div>
<div class="bg d-none">
  <div class="container bg-light col-6 popup">
    <h2>Create a new list</h2>
    <span class="x"><%= icon('fas', 'times-circle') %></span>
    <%= simple_form_for @list do |f| %>
      <%= f.input :name, label: icon('fas', 'file-signature'), placeholder: 'list name' %> <br>
      <%= f.input :image, as: :file, label: icon('fas', 'image') %>
      <br>
      <%= f.button :submit, class: 'btn btn-primary btn-sm'  %>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>Create a list</h1>
<div class="container bg-light col-6">
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :image, as: :file %>
  <%= f.button :submit, class: 'btn btn-primary btn-sm'  %>
<% end %>
</div>
<br>
<%= link_to '< Back', lists_path, class: "btn btn-outline-primary" %>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @list.image.key, height: 300, crop: :fill%>');">
  <div class="container">
    <h1><%= @list.name %></h1>
    <%= link_to raw('<i class="far fa-trash-alt"></i>'), list_path(@list), method: :delete, data: { confirm: "Are you sure to remove #{@list.name}?" }, class: 'btn btn-outline-danger btn-sm m-3' %>
  </div>
</div>
<br>
<div class="container bg-light d-flex flex-wrap rounded">
    <% @list.bookmarks.each do |bm| %>
      <div class='bm-col'>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= bm.movie.poster_url %>')">
          <div class="d-flex flex-column justify-content-between ml-2">
            <h4><%= bm.movie.title %></h4>
          <h5>rated: <%= bm.movie.rating %></h5>
          <h5 class="scroll"><%= bm.comment %></h5>
          </div>
            <%= link_to raw('<i class="far fa-trash-alt"></i>'), bookmark_path(bm), method: :delete, data: { confirm: "Remove #{bm.movie.title}?" }, class: 'btn btn-danger btn-sm' %>
        </div>
        <p class="scroll bm-p"><%= bm.movie.overview %></p>
      </div>
    <% end %>
    <div class="bm-col">
      <div class='btn btn-outline-primary btn-bookmark' id='show'><%= icon('fas', 'plus') %></div>
    </div>
</div>
<br>
<div class="bg d-none">
  <div class="container bg-light col-6 popup">
    <h2>Search for a movie</h2>
    <span class="x"><%= icon('fas', 'times-circle') %></span>
      <%= simple_form_for :search, url: (new_movie_path), method: "GET", html: { class: 'form-inline d-flex' } do |f| %>
        <%= f.hidden_field :list_id, value: @list.id %>
        <%= f.input :title, label: icon('fas', 'video'), placeholder: "enter a title" %>
        <button action='submit' disabled='disabled' class='btn btn-primary dis'><%= icon('fab', 'sistrix') %></button>
      <% end %>
  </div>
</div>

app/views/movies/index.html.erb
<h1>Add a movie to <%= @list.name %></h1>
<div class="container col-12 d-flex flex-wrap justify-content-center" style="padding-bottom: 65px;">
  <% if @movies.empty? %>
    <p>No results found for "<%= params[:passed_parameter][:query] %>"</p>
  <% else %>
    <% @movies.each do |m| %>
      <div class='col-5 movie-card'>
        <div class="card-category col-4" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= m['poster_url'] %>)"></div>
        <div class="description">
          <div class="card-h p-1 scroll">
            <h4><%= m['title'] %></h4>
          </div>
          <div class="card-p p-1 scroll">
            <p><%= m['overview'] %></p>
          </div>
        </div>
        <%= link_to icon('fas', 'plus'), new_list_bookmark_path(list_id: @list.id, movie_id: m['id']), class: "btn btn-success btn-movie" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/movies/new.html.erb
<h1><%= icon('fab', 'sistrix') %> Search for a movie for <%= @list.name %></h1>
<div class="container bg-light col-6">
  <div>
    <%= simple_form_for :search, method: "GET", html: { class: 'form-inline' } do |f| %>
      <%= f.input :title, label: '', placeholder: "enter a title" %>
      <%= f.hidden_field :list_id, value: @list.id %>
      <%= f.submit 'search', disabled: 'disabled', class: "btn btn-primary dis"%>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <%= link_to icon('fas','home'), :lists, class: "btn btn-outline-primary" %>
  <%= link_to icon('fas', 'sign-out-alt'), destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %>
</div>
<div class="footer-placeholder"></div>